// Copies the `abi` field of Foundry artifacts into `abis/<Name>.ts` as `as const` arrays so Ponder and viem can
// type event args. Run `forge build` in contracts/ first, then `pnpm abis`. The generated files are committed so the
// indexer builds without a Solidity toolchain.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = resolve(here, "..", process.env.CONTRACTS_OUT ?? "../../contracts/out");
const target = resolve(here, "..", "abis");

// [artifact name, export name]. Token-layer contracts are typed from their interfaces until they are deployed.
const artifacts = [
  ["DealVault", "DealVault"],
  ["HybridVault", "HybridVault"],
  ["HybridFees", "HybridFees"],
  ["HybridFactory", "HybridFactory"],
  ["CollateralRegistry", "CollateralRegistry"],
  ["FeeSink", "FeeSink"],
  ["EntryRouter", "EntryRouter"],
  ["IsGAGE", "sGAGE"],
  ["IDrip", "Drip"],
  ["IEmissions", "Emissions"],
  ["IDealRewards", "DealRewards"],
  ["ILPRewards", "LPRewards"],
  ["ILPStreamer", "LPStreamer"],
  ["IBuyback", "Buyback"],
  ["ICreatorFeeSplitter", "CreatorFeeSplitter"],
  ["IReinvestRouter", "ReinvestRouter"],
  ["ISeedTimelock", "SeedTimelock"],
  ["IERC721", "ERC721"],
  ["IPositionManager", "PositionManager"],
  ["IERC20Metadata", "ERC20Metadata"],
];

mkdirSync(target, { recursive: true });
let written = 0;
for (const [artifact, name] of artifacts) {
  const file = resolve(outDir, `${artifact}.sol`, `${artifact}.json`);
  if (!existsSync(file)) {
    console.error(`missing artifact ${file}; run \`forge build\` in contracts/ first`);
    process.exitCode = 1;
    continue;
  }
  const { abi } = JSON.parse(readFileSync(file, "utf8"));
  const body = `// Generated by scripts/sync-abis.mjs from contracts/out/${artifact}.sol/${artifact}.json. Do not edit.\n` +
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`;
  writeFileSync(resolve(target, `${name}.ts`), body);
  written += 1;
}
console.log(`wrote ${written}/${artifacts.length} ABI files to ${target}`);
