// Generated by scripts/sync-abis.mjs from contracts/out/IDealRewards.sol/IDealRewards.json. Do not edit.
export const DealRewardsAbi = [
  {
    "type": "function",
    "name": "MAX_REWARD_SHARE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "USDG_UNIT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "dripIdOf",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "party",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "effectiveRates",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IDealRewards.EpochRates",
        "components": [
          {
            "name": "rate7",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rate21",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "priceUSDGPerSGAGE",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lenderShareBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "set",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "epochRates",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IDealRewards.EpochRates",
        "components": [
          {
            "name": "rate7",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "rate21",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "priceUSDGPerSGAGE",
            "type": "uint128",
            "internalType": "uint128"
          },
          {
            "name": "lenderShareBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "set",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quote",
    "inputs": [
      {
        "name": "term",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "fee",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "outputs": [
      {
        "name": "reward",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "budgetAvailable",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "budgetRemaining",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "register",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "registered",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rewardOf",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "total",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "lenderAmount",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "borrowerAmount",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setEpochRates",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "rate7",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "rate21",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "priceUSDGPerSGAGE",
        "type": "uint128",
        "internalType": "uint128"
      },
      {
        "name": "lenderShareBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "RatesSet",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "rate7",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "rate21",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "priceUSDGPerSGAGE",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "lenderShareBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Registered",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "epoch",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "term",
        "type": "uint32",
        "indexed": false,
        "internalType": "uint32"
      },
      {
        "name": "fee",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "reward",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "lenderAmount",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "borrowerAmount",
        "type": "uint128",
        "indexed": false,
        "internalType": "uint128"
      },
      {
        "name": "budgetExhausted",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AlreadyRegistered",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DealNotFunded",
    "inputs": [
      {
        "name": "dealId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRates",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RatesForPastEpoch",
    "inputs": [
      {
        "name": "epoch",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
